# -*- coding: utf-8 -*-
"""via-certificate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dmOEDzy2gv9VSfTdMMglp2R2-6XsvDyw

This file generates VIA certificates using the Pillows library for various volunteer activities
"""

from google.colab import auth
from google.colab import drive
drive.mount('/content/drive')
auth.authenticate_user()

import gspread

from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

website = gc.open('Volunteer VIA Claims').worksheet("Website Form")
website_rows = website.get_all_values()

bot = gc.open('Volunteer VIA Claims').worksheet("Herbert Bot")
bot_rows = bot.get_all_values()

rows = website_rows + bot_rows

name_list = [row[6] for row in rows[1:] if row[10] == 'Y' and row[8] == 'N']
date_list = [row[3] for row in rows[1:] if row[10] == 'Y' and row[8] == 'N']
activity_list = [row[4] for row in rows[1:] if row[10] == 'Y' and row[8] == 'N']
hours_list = [row[7] for row in rows[1:] if row[10] == 'Y' and row[8] == 'N']
hash_list = [row[14] for row in rows[1:] if row[10] == 'Y' and row[8] == 'N']

print(name_list, activity_list, hash_list)

from PIL import Image
from PIL import ImageFont
from PIL import ImageDraw
import sys
from datetime import datetime
from pytz import timezone

name, activity, hours = range(3)

signature_tyd = "/content/drive/MyDrive/ASSETS/via-certificate/signature_tyd.png"
signature_se = "/content/drive/MyDrive/ASSETS/via-certificate/signature_se.png"
signature_st = "/content/drive/MyDrive/ASSETS/via-certificate/signature_st.png"
signature_ot = "/content/drive/MyDrive/ASSETS/via-certificate/signature_ot.png"
signature_gd = "/content/drive/MyDrive/ASSETS/via-certificate/signature_gd.png"

certificate_template = "/content/drive/MyDrive/ASSETS/via-certificate/template.png"
font_type = "/content/drive/MyDrive/ASSETS/via-certificate/Montserrat-Regular.ttf"

activity_list_map = {"card-making": "Card Making Session","scrapbook-edition":"Scrapbook Edition Cycle","distribution":"Monthly Distribution","crochet":"HYGM Crochet Session","goes-digital":"Goes Digital Cycle"}

for hash in hash_list:
  name = name_list[hash_list.index(hash)]
  date = date_list[hash_list.index(hash)]
  hours = hours_list[hash_list.index(hash)]
  hash = hash_list[hash_list.index(hash)]

  try:
    activity = activity_list_map[activity_list[hash_list.index(hash)]]
  except:
    continue
  
  activities = {

# Content for Card Making Sessions
"Card Making Session":
  [f'''On {date}:

The individual volunteered his/her time to participate in
our card making session, where he/she penned down a few
heartfelt messages and created Hey, You Got Mail! cards as part of
our card sending initiative.

The cards were subsequently sent on their behalf to seniors from
Hey, You Got Mail's list of elderly beneficiaries, including
nursing homes, senior activity centres and rental flats. The
event was conducted in a safe manner
aligning to prevailing COVID-19 regulations.''','''Tan Wei Lin,
Director of Strategy''', signature_st],


# Content for Monthly Distributions
"Monthly Distribution":
  [f'''On {date}:

  The individual volunteered his/her time to participate in our
  monthly heartland distributions to socially isolated seniors as part
  of Hey, You Got Mail's "To Your Doorstep" initiative.

  He/she actively played a part in giving out handwritten cards and
  COVID-19 essential products to socially isolated seniors living in
  rental flats or studio apartments. The event was conducted
  in a safe manner aligning to prevailing COVID-19 regulations.''','''Aldrich Yu,
  Head of To Your Doorstep''',signature_tyd],


# Content for Scrapbook Edition
"Scrapbook Edition Cycle":
  [f'''On {date}:

The individual volunteered his/her time to participate in our
Hey, You Got Mail! : Scrapbook Edition cycle, where he/she formed a
long term relationship with a paired senior across
a minimum period of two months.

The individual visited the senior occasionally to engage the senior
in various activities, recording all their memories in the form of
a scrapbook, which was kept by the senior.
The event was conducted in a safe manner aligning to prevailing
COVID-19 regulations and the seniors were sourced from
Hey, You Got Mail's recognized list of partner beneficiaries.''',''' Devanshu Bisht,
Head of Scrapbook Edition''', signature_se],


# Content for Crochet Session
"HYGM Crochet Session":
  [f'''On {date}:

The individual volunteered his/her time to participate in our 
Hey, You Got Mail! Crochet sessions where he/she spent time crocheting 
household friendly items for socially isolated seniors.

The designs produced were distributed to socially isolated seniors 
from Hey, You Got Mail's recognized list of partner beneficiaries. 
The event was conducted in a safe manner aligning to prevailing 
COVID-19 regulations.''', ''' Triston Tan,
Director of Liaisons & Outreach''', signature_ot],



# Content for Goes Digital
"Goes Digital Cycle":
  [f'''On {date}:

The individual volunteered his/her time to participate in our
Hey, You Got Mail! Goes Digital cycle, where he/she attended a physical
training session prior to the start of the cycle.

The individual learnt how to communicate and interact with seniors from 
Hey, You Got Mail's recognized list of partner beneficiaries
in a tactful manner.
The event was conducted in a safe manner aligning to prevailing
COVID-19 regulations.''',''' Teo Eu Tint,
Head of Goes Digital''', signature_gd]
}


  activity_desc = activities[activity_list_map[activity_list[hash_list.index(hash)]]][0]

  img = Image.open(certificate_template)
  signature = Image.open(activities[activity_list_map[activity_list[hash_list.index(hash)]]][2])
  draw = ImageDraw.Draw(img)
  size_64 = ImageFont.truetype(font_type, 64)
  size_32 = ImageFont.truetype(font_type, 32)
  size_28 = ImageFont.truetype(font_type, 28)
  color = (226,131,109)

  # drawing the volunteer name
  draw.text((360, 700),name,color,font=size_64)

  # drawinng the volunteer hours
  draw.text((920, 805),hours,color,font=size_64)

  #drawing the volunteer activity
  draw.text((385, 960),activity,color,font=size_64)

  # drawing the activity description
  draw.multiline_text((210,1095),activities[activity_list_map[activity_list[hash_list.index(hash)]]][0],color,font=size_32)

  # drawing the volunteer date
  draw.text((345, 1755),date,(0,0,0),font=size_28)

  # drawing the approvers name
  draw.multiline_text((230, 1870),activities[activity_list_map[activity_list[hash_list.index(hash)]]][1],(0,0,0),font=size_28, align='center')

  # inserting signature of approver
  img.paste(signature,(235,1650),signature)

  # inserting certificate id / hash
  draw.multiline_text((475, 1950),hash,color,font=size_28, align='center')
  
  final = img.convert('RGB')
  # final.save(f'''/content/drive/MyDrive/VIA CERTIFICATES/{name.replace('/','')}.pdf''')
  print(f"Generating Certificate for {name} - {hash}")
  final.save(f'''/content/drive/MyDrive/VIA CERTIFICATES/{hash}.pdf''')
  print(f"Saved")